name: Run leerjavascript.py

on:
  workflow_dispatch:

  schedule:
    # Corre cada hora de 8 a 22
    - cron: '0 8-22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Aumentar el tiempo de espera para evitar fallos por tiempo

    permissions:
      # Permisos necesarios
      contents: write  # Permitir escritura en el contenido del repositorio

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3  # Clona el repositorio

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Instalar la versión de Python necesaria

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser  # Instalar Chrome
          sudo apt-get install -y chromium-chromedriver  # Instalar ChromeDriver
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute Python script
        run: python leerjavascript.py
        env:
          DISPLAY: :99.0  # Necesario para algunos entornos sin interfaz gráfica

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "CAMBIOS PLAN" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
